# Generated by Django 4.2.30 on 2026-07-10 10:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'base_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='district',
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='The price must be greater than zero.'), django.core.validators.MaxValueValidator(Decimal('100000.00'), message='The price cannot exceed 100,000.')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Wohnung'), ('house', 'Haus'), ('room', 'Zimmer')], db_index=True, default='apartment', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1, message='The number of rooms must be at least 1.'), django.core.validators.MaxValueValidator(15, message='The number of rooms cannot exceed 15.')]),
        ),
    ]
